import {
  faBicycle,
  faBus,
  faCar,
  faCube,
  faTruckPickup,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const icons = {
  bike: faBicycle,
  bus: faBus,
  car: faCar,
  rickshaw: faTruckPickup,
  shipping: faCube,
};
const categoryArray = [
  {
    label: "Select",
    value: "",
  },
  {
    label: "category 1",
    value: "category 1",
  },
];

const subCategoryArray = [
  {
    label: "Select1",
    value: "",
  },
  {
    label: "category 1",
    value: "category 1",
  },
];

const priorityArray = [
  {
    label: "Low",
    value: "LOW",
  },
  {
    label: "Medium",
    value: "MEDIUM",
  },
  {
    label: "High",
    value: "HIGH",
  },
];

const workTypeArray = [
  {
    label: "Ongoing Applied Work",
    value: "OAW",
  },
  {
    label: "Ongoing Posted Work",
    value: "OPW",
  },
  {
    label: "Completd Applied Work",
    value: "CAW",
  },
  {
    label: "Completd Posted Work",
    value: "CPW",
  },
];

const genderArray = [
  {
    label: "Male",
    value: "MALE",
  },
  {
    label: "Female",
    value: "FEMALE",
  },
  {
    label: "Any",
    value: "ANY",
  },
  {
    label: "Other",
    value: "OTHER",
  },
];

const criticalityArray = [
  {
    label: "Low",
    value: "Low",
  },
  {
    label: "Moderate",
    value: "Moderate",
  },
  {
    label: "High",
    value: "High",
  },
  {
    label: "Critical",
    value: "Critical",
  },
];

const jobTypeArray = [
  {
    label: "Contractual",
    value: "CONTRACTUAL",
  },
  {
    label: "Permanent",
    value: "PERMANENT",
  },
];

const durationPeriodArray = ["SHORT", "MEDIUM", "LONG", "ADHOC"];

const stateArray = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

const jobType = [
  "Full-Time",
  "Part-Time",
  "Temporary",
  "Freelance",
  "Internship",
];

const jobMode = ["Hybrid", "Onsite", "Work From Home"];
const jobShift = ["Day", "Night", "Flexible"];

const payroll = ["Company Payroll", "3rd Party Payroll", "No Payroll"];

const experienceRequired = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "30+",
];

const addressType = ["Permanent", "Temporary"];

const contactStatusType = ["ACTIVE", "PASSIVE"];

const vehicleType = ["AUTO", "BIKE", "CAR", "PICKUP", "TRUCK"];

const healthEntityType = ["INDIVIDUAL", "CLINIC", "LAB", "HOSPITAL"];

const shippingFee = 40;

const platformFee = 5;

const userTypeArray = [
  {
    label: "Individual",
    value: "INDIVIDUAL",
  },
  {
    label: "Family",
    value: "FAMILY",
  },
  {
    label: "Community",
    value: "Community",
  },
];

const userSecurityType = [
  {
    label: "Change Password",
    value: "P",
  },
  {
    label: "Delete Account",
    value: "D",
  },
];

const userDeleteType = [
  {
    label:
      "Do you wantt to delete your account only (your account will be deactivated)",
    value: "DU",
  },
  {
    label:
      "Do you wantt to delete your account along with every data (your personal info will be deleted but your work history will be stored username will be there as masked data rest data will be deleted)",
    value: "DA",
  },
];

const vehicleCategories = [
  "LIGHT MOTOR VEHICLE",
  "HEAVY MOTOR VEHICLE",
  "Motorcycle Without Gear",
  "Motorcycle With Gear",
  "Light Motor Vehicle (Non-Transport)",
  "Light Motor Vehicle (Transport)",
  "Heavy Motor Vehicle",
  "Heavy Passenger Motor Vehicle",
  "Heavy Transport Vehicle",
  "Medium Goods Vehicle",
  "Medium Passenger Vehicle",
  "Electric Rickshaw",
];

const fuels = [
  "DIESEL",
  "PETROL",
  "CNG",
  "LPG",
  "ELECTRIC",
  "HYBRID",
  "BIO-DIESEL",
  "ETHANOL",
  "HYDROGEN",
];

const strokes = ["2 Stroke", "4 Stroke"];

const permitType = ["National Permit", "State Permit"];
const purposeofUse = ["Passenger Transport", "Goods Transport"];

const puc = ["Yes", "No"];

const vehicleOptions = [
  {
    code: "MCWOG",
    class: "Motorcycle Without Gear",
    icon: <FontAwesomeIcon icon={icons.bike} />,
  },
  {
    code: "MCWG",
    class: "Motorcycle With Gear",
    icon: <FontAwesomeIcon icon={icons.bike} />,
  },
  {
    code: "LMV-NT",
    class: "Light Motor Vehicle (Non-Transport)",
    icon: <FontAwesomeIcon icon={icons.car} />,
  },
  {
    code: "LMV-TR",
    class: "Light Motor Vehicle (Transport)",
    icon: <FontAwesomeIcon icon={icons.car} />,
  },
  {
    code: "HMV",
    class: "Heavy Motor Vehicle",
    icon: <FontAwesomeIcon icon={icons.shipping} />,
  },
  {
    code: "HPMV",
    class: "Heavy Passenger Motor Vehicle",
    icon: <FontAwesomeIcon icon={icons.bus} />,
  },
  {
    code: "HTV",
    class: "Heavy Transport Vehicle",
    icon: <FontAwesomeIcon icon={icons.shipping} />,
  },
  {
    code: "MGV",
    class: "Medium Goods Vehicle",
    icon: <FontAwesomeIcon icon={icons.shipping} />,
  },
  {
    code: "MPV",
    class: "Medium Passenger Vehicle",
    icon: <FontAwesomeIcon icon={icons.bus} />,
  },
  {
    code: "ERickshaw",
    class: "Electric Rickshaw",
    icon: <FontAwesomeIcon icon={icons.rickshaw} />,
  },
];

const buttons = [
  { label: "Driving Licence", url: "/mylicense" },
  { label: "National Id", url: "/national-id" },
  { label: "Pan Card", url: "/pan-card" },
];

const buttons1 = [
  { label: "Council License", url: "/council-certificate" },
  { label: "Professional Certificate", url: "/professional-certificate" },
];

const buttons2 = [
  { label: "Daily Ride", url: "/myRides" },
  { label: "Digital Stand", url: "/digitalStand" },
];

const buttons3 = [
  { label: "Prescription Reports", url: "/prescriptionReports" },
  { label: "Lab Reports", url: "/labReports" },
];

const doctorSpecialities = [
  { value: "dentist", label: "Dentist", icon: "tooth-solid" },
  { value: "neurologist", label: "Neurologist", icon: "brain-solid" },
  { value: "orthopedic", label: "Orthopedic", icon: "bone-solid" },
  { value: "surgeon", label: "Surgeon", icon: "user-doctor-solid" },
  { value: "cardiologist", label: "Cardiologist", icon: "heart-pulse-solid" },
  { value: "pulmonologist", label: "Pulmonologist", icon: "lungs-solid" },
  { value: "pharmacist", label: "Pharmacist", icon: "capsules-solid" },
  {
    value: "general-physician",
    label: "General Physician",
    icon: "stethoscope-solid",
  },
  { value: "radiologist", label: "Radiologist", icon: "x-ray-solid" },
  { value: "dermatologist", label: "Dermatologist", icon: "bandage-solid" },
  {
    value: "ophthalmologist",
    label: "Ophthalmologist (Eye Doctor)",
    icon: "eye-solid",
  },
  {
    value: "ent-specialist",
    label: "ENT Specialist",
    icon: "head-side-cough-solid",
  },
  { value: "pediatrician", label: "Pediatrician", icon: "baby-solid" },
  { value: "oncologist", label: "Oncologist", icon: "ribbon-solid" },
  {
    value: "gastroenterologist",
    label: "Gastroenterologist",
    icon: "bacterium-solid",
  },
  { value: "endocrinologist", label: "Endocrinologist", icon: "vial-solid" },
  { value: "psychiatrist", label: "Psychiatrist", icon: "user-injured-solid" },
  { value: "gynecologist", label: "Gynecologist", icon: "person-dress-solid" },
  {
    value: "nephrologist",
    label: "Nephrologist (Kidney Specialist)",
    icon: "droplet-solid",
  },
  { value: "hematologist", label: "Hematologist", icon: "microscope-solid" },
  { value: "urologist", label: "Urologist", icon: "person-solid" },
  {
    value: "rheumatologist",
    label: "Rheumatologist",
    icon: "hand-holding-medical-solid",
  },
  {
    value: "allergist-immunologist",
    label: "Allergist/ Immunologist",
    icon: "hand-dots-solid",
  },
  {
    value: "emergency-medicine",
    label: "Emergency Medicine",
    icon: "truck-medical-solid",
  },
  {
    value: "infectious-disease-specialist",
    label: "Infectious Disease Specialist",
    icon: "viruses-solid",
  },
  {
    value: "anesthesiologist",
    label: "Anesthesiologist",
    icon: "bed-pulse-solid",
  },
  { value: "pathologist", label: "Pathologist", icon: "dna-solid" },
  {
    value: "chiropractor",
    label: "Chiropractor",
    icon: "handshake-angle-solid",
  },
  {
    value: "dietitian-nutritionist",
    label: "Dietitian/ Nutritionist",
    icon: "apple-whole-solid",
  },
  {
    value: "occupational-therapist",
    label: "Occupational Therapist",
    icon: "people-arrows-solid",
  },
  { value: "podiatrist", label: "Podiatrist", icon: "shoe-prints-solid" },
  {
    value: "speech-therapist",
    label: "Speech Therapist",
    icon: "comments-solid",
  },
  {
    value: "physical-therapist",
    label: "Physical Therapist",
    icon: "person-running-solid",
  },
  {
    value: "plastic-surgeon",
    label: "Plastic Surgeon",
    icon: "paintbrush-solid",
  },
  {
    value: "neonatologist",
    label: "Neonatologist",
    icon: "baby-carriage-solid",
  },
];

const nurseSpecialties = [
  {
    value: "geriatric-nurse",
    label: "Geriatric Nurse",
    icon: "person-walking-with-cane-solid",
  },
  {
    value: "hospice-palliative-care-nurse",
    label: "Hospice/Palliative Care Nurse",
    icon: "hands-praying-solid",
  },
  {
    value: "home-health-nurse",
    label: "Home Health Nurse",
    icon: "house-medical-solid",
  },
  {
    value: "community-health-nurse",
    label: "Community Health Nurse",
    icon: "users-solid",
  },
  { value: "cardiac-nurse", label: "Cardiac Nurse", icon: "heart-pulse-solid" },
  { value: "dialysis-nurse", label: "Dialysis Nurse", icon: "droplet-solid" },
  {
    value: "rehabilitation-nurse",
    label: "Rehabilitation Nurse",
    icon: "person-running-solid",
  },
  { value: "oncology-nurse", label: "Oncology Nurse", icon: "ribbon-solid" },
  {
    value: "psychiatric-nurse",
    label: "Psychiatric Nurse",
    icon: "brain-solid",
  },
  {
    value: "public-health-nurse",
    label: "Public Health Nurse",
    icon: "globe-solid",
  },
  { value: "iv-therapy-nurse", label: "IV Therapy Nurse", icon: "vial-solid" },
  {
    value: "wound-care-nurse",
    label: "Wound Care Nurse",
    icon: "bandage-solid",
  },
  {
    value: "occupational-health-nurse",
    label: "Occupational Health Nurse",
    icon: "briefcase-medical-solid",
  },
  {
    value: "pain-management-nurse",
    label: "Pain Management Nurse",
    icon: "syringe-solid",
  },
  {
    value: "telehealth-nurse",
    label: "Telehealth Nurse",
    icon: "phone-flip-solid",
  },
  {
    value: "neonatal-nurse",
    label: "Neonatal Nurse",
    icon: "baby-carriage-solid",
  },
];

const dietitianSpecialties = [
  {
    value: "clinical-dietitian",
    label: "Clinical Dietitian",
    icon: "hospital-solid",
  },
  {
    value: "pediatric-dietitian",
    label: "Pediatric Dietitian",
    icon: "child-solid",
  },
  {
    value: "sports-dietitian",
    label: "Sports Dietitian",
    icon: "dumbbell-solid",
  },
  {
    value: "renal-dietitian",
    label: "Renal Dietitian",
    icon: "clover-solid",
  },
  {
    value: "oncology-dietitian",
    label: "Oncology Dietitian",
    icon: "ribbon-solid",
  },
  {
    value: "geriatric-dietitian",
    label: "Geriatric Dietitian",
    icon: "person-walking-with-cane-solid",
  },
  {
    value: "community-dietitian",
    label: "Community Dietitian",
    icon: "users-solid",
  },
  {
    value: "public-health-dietitian",
    label: "Public Health Dietitian",
    icon: "globe-solid",
  },
  {
    value: "weight-management-dietitian",
    label: "Weight Management Dietitian",
    icon: "scale-balanced-solid",
  },
  {
    value: "diabetes-educator-dietitian",
    label: "Diabetes Educator Dietitian",
    icon: "droplet-solid",
  },
  {
    value: "food-service-dietitian",
    label: "Food Service Dietitian",
    icon: "utensils-solid",
  },
  {
    value: "integrative-and-functional-dietitian",
    label: "Integrative and Functional Dietitian",
    icon: "leaf-solid",
  },
  {
    value: "research-dietitian",
    label: "Research Dietitian",
    icon: "flask-solid",
  },
  {
    value: "cardiovascular-dietitian",
    label: "Cardiovascular Dietitian",
    icon: "heart-pulse-solid",
  },
  {
    value: "telehealth-dietitian",
    label: "Telehealth Dietitian",
    icon: "phone-flip-solid",
  },
];

const labTestData = [
  {
    value: "complete-blood-count-cbc",
    label: "Complete Blood Count (CBC)",
    icon: "vials-solid",
  },
  { value: "lipid-panel", label: "Lipid Panel", icon: "heart-pulse-solid" },
  {
    value: "basic-metabolic-panel-bmp",
    label: "Basic Metabolic Panel (BMP)",
    icon: "calculator-solid",
  },
  {
    value: "liver-function-test-lft",
    label: "Liver Function Test (LFT)",
    icon: "liver",
  },
  {
    value: "thyroid-function-test",
    label: "Thyroid Function Test",
    icon: "shield-solid",
  },
  { value: "urinalysis", label: "Urinalysis", icon: "flask-solid" },
  {
    value: "coagulation-panel",
    label: "Coagulation Panel",
    icon: "droplet-solid",
  },
  { value: "covid-19-test", label: "COVID-19 Test", icon: "viruses-solid" },
  { value: "allergy-test", label: "Allergy Test", icon: "bandage-solid" },
  {
    value: "blood-glucose-test",
    label: "Blood Glucose Test",
    icon: "syringe-solid",
  },
  {
    value: "electrolyte-panel",
    label: "Electrolyte Panel",
    icon: "bolt-solid",
  },
  { value: "hiv-test", label: "HIV Test", icon: "ribbon-solid" },
  { value: "pregnancy-test", label: "Pregnancy Test", icon: "baby-solid" },
  { value: "vitamin-d-test", label: "Vitamin D Test", icon: "sun-solid" },
  { value: "cholesterol-test", label: "Cholesterol Test", icon: "egg-solid" },
  {
    value: "hemoglobin-a1c-test",
    label: "Hemoglobin A1C Test",
    icon: "chart-bar-solid",
  },
];

const pharmacistSpecialtyData = [
  {
    value: "medication-therapy-management",
    label: "Medication Therapy Management (MTM)",
  },
  { value: "immunization-services", label: "Immunization Services" },
  { value: "pharmacokinetics", label: "Pharmacokinetics" },
  { value: "compounding-pharmacy", label: "Compounding Pharmacy" },
  { value: "clinical-trial-management", label: "Clinical Trial Management" },
  { value: "drug-interaction-screening", label: "Drug Interaction Screening" },
  { value: "patient-counseling", label: "Patient Counseling" },
  { value: "pain-management", label: "Pain Management" },
  { value: "oncology-pharmacy", label: "Oncology Pharmacy" },
  {
    value: "infectious-disease-pharmacy",
    label: "Infectious Disease Pharmacy",
  },
  { value: "psychiatric-pharmacy", label: "Psychiatric Pharmacy" },
  { value: "cardiovascular-pharmacy", label: "Cardiovascular Pharmacy" },
  { value: "pediatric-pharmacy", label: "Pediatric Pharmacy" },
  { value: "geriatric-pharmacy", label: "Geriatric Pharmacy" },
  { value: "diabetes-management", label: "Diabetes Management" },
  { value: "anticoagulation-management", label: "Anticoagulation Management" },
];

const units = ["Piece", "Plate", "Kg", "Gram", "Litre", "Ml", "Dozen"];
const productDisplayType = ["VEG", "NON-VEG"];

const categories = [
  "LIGHT MOTOR VEHICLE",
  "HEAVY MOTOR VEHICLE",
  "Motorcycle Without Gear",
  "Motorcycle With Gear",
  "Light Motor Vehicle (Non-Transport)",
  "Light Motor Vehicle (Transport)",
  "Heavy Motor Vehicle",
  "Heavy Passenger Motor Vehicle",
  "Heavy Transport Vehicle",
  "Medium Goods Vehicle",
  "Medium Passenger Vehicle",
  "Electric Rickshaw",
];

const weekDays = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

const vehicleBodies = [
  "AUTO",
  "SUV",
  "HATCHBACK",
  "MUV",
  "TRUCK",
  "BUS",
  "VAN",
  "MOTORCYCLE",
  "TRAILER",
  "TANKER",
];


const returnReason = [
  "Item damaged during delivery",
  "Received wrong product",
  "Product not as described",
  "Defective or malfunctioning item",
  "Missing parts or accessories",
  "Change of mind",
  "Better price found elsewhere",
  "Size or fit issue",
  "Late delivery",
  "Duplicate order",
  "Received an empty package",
  "Product quality not satisfactory",
  "Unwanted gift",
  "Incorrect item quantity",
];

const cancellationReasons = [
  "Found a better deal elsewhere",
  "Delay in delivery time",
  "No longer needed the product",
  "Ordered by mistake",
  "Changed mind about the purchase",
  "Issues with payment or transaction",
  "Incorrect shipping address provided",
  "Product added to the wrong order",
  "Duplicate order placed",
  "Item out of stock after ordering",
  "Requested customization not available",
  "Customer service experience was unsatisfactory",
  "Decided to buy from a local store",
  "Technical issues with the website during order",
  "Concern about product quality after ordering",
];

const orderFilter = [
  {
    label: "Last 30 Days",
    value: "30days",
  },
  {
    label: "Last 3 Months",
    value: "3months",
  },
  {
    label: "Older",
    value: "Older",
  },
  {
    label: "Cancelled",
    value: "CANCELLED",
  },
  {
    label: "Returned",
    value: "RETURNED",
  },
  {
    label: "Delivered",
    value: "DELIVERED",
  },
];

const foodType = [
  { label: "Indian" },
  { label: "Italian" },
  { label: "Fast Food" },
  { label: "South Indian" },
  { label: "Mexican" },
  { label: "Chinese" },
  { label: "Mediterranean" },
];

const BrandsList = [
  { label: "Brand 1" },
  { label: "Brand 2" },
  { label: "Brand 3" },
  { label: "Brand 4" },
  { label: "Brand 5" },
  { label: "Brand 6" },
  { label: "Brand 7" },
];

const storeType = ["INDIVIDUAL", "ORGANIZATION", "BRAND"];

const appointmentTypes = [
  "By Clinic",
  "By Hospital",
  "By Health Camp",
  "By Doctor",
];

const contactConnectType = ["FAMILY", "SOCIETY"];
const familyRelationships = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Son",
  "Daughter",
  "Grandfather",
  "Grandmother",
  "Uncle",
  "Aunty",
  "Cousin",
  "Nephew",
  "Niece",
  "Husband",
  "Wife",
  "Friend",
  "Partner",
  "Colleague",
  "Neighbor",
  "Guardian",
  "Mentor",
  "Teacher",
  "Student",
  "Sibling",
];

const societyRole = [
  "Secretary",
  "Treasurer",
  "Resident",
  "Owner",
  "Caretaker",
  "Watchman",
  "Gardener",
  "Electrician",
  "Plumber",
  "Housekeeper",
  "Maintenance Staff",
  "Security Guard",
  "Visitor",
  "Vendor",
  "Delivery Personnel",
  "Driver",
  "Cleaner",
  "Janitor",
  "Committee Member",
  "Manager",
  "Supervisor",
];

const roles = ["STUDENT", "TEACHER", "PARENT", "INSTRUCTOR", "ADMIN"];

const difficultyLevel = ["Easy", "Medium", "Hard"];
const noOfQos = ["1", " 2", " 5", " 10", " 20", " 30", " 50"];

const time = [
  "Daily 1-2 hrs",
  "0-2 hrs / week",
  "3-5 hrs / week",
  "5+ hrs / week",
  "I haven't decided yet",
];

const courseCategory = [
  "Web Development",
  "Data Science",
  "Graphic Design",
  "Digital Marketing",
  "AI and Machine Learning",
];

const languages = [
  { value: "English", label: "English" },
  { value: "Spanish", label: "Spanish" },
  { value: "French", label: "French" },
];

const DEcategories = [
  { value: "IT & Software", label: "IT & Software" },
  { value: "Finance", label: "Finance" },
  { value: "Design", label: "Design" },
  { value: "Development", label: "Development" },
  { value: "Business", label: "Business" },
  { value: "Marketing", label: "Marketing" },
  { value: "Personal Development", label: "Personal Development" },
  { value: "Teaching & Academics", label: "Teaching & Academics" },
];

const skillLevels = [
  { value: "beginner", label: "Beginner" },
  { value: "intermediate", label: "Intermediate" },
  { value: "advanced", label: "Advanced" },
];

const amounts = [
  { value: "1000", label: "1000" },
  { value: "2000", label: "2000" },
  { value: "3000", label: "3000" },
];

const currencies = [
  { value: "INR", label: "INR" },
  { value: "USD", label: "USD" },
  { value: "AUD", label: "AUD" },
];

const courseRatings = [
  { value: "All Ratings", label: "All Ratings" },
  { value: "5 Stars", label: "Five Stars" },
  { value: "4 Stars", label: "Four Stars" },
  { value: "3 Stars", label: "Three Stars" },
  { value: "2 Stars", label: "Two Stars" },
  { value: "1 Star", label: "One Star" },
];

const QnsSortBy = ["Sort by most recent", "Sort by recommended"];

const QnsTypeSortBy = [
  "MCQ",
  "Yes/No",
  "Short Questions",
  "Fill in the blanks",
];

const courses = ["Python", "Java", "SQL"];

const QnsFilterBy = ["Current Lecture", "All Lectures"];

const cameraType = [
  "Webcam",
  "Smartphone Camera",
  "Action Camera",
  "Mirrorless",
  "DSLR",
  "I don't know",
];

const microphoneType = [
  "In-build Microphone",
  "Dynamic Microphone",
  "USB Microphone",
  "Shotgun Microphone",
  "I don't know",
];

const operatingSystem = [
  "Windows",
  "macOS",
  "Linux",
  "Android",
  "iOS",
  "I don't know",
];

const filmingOptions = [
  {
    label: "I'm filming my computer/laptop screen",
    value: "laptopScreen",
  },
  {
    label: "I'm filming myself or another person",
    value: "myself",
  },
  {
    label: "I'm filming an activity (e.g. chemistry practical)",
    value: "activity",
  },
];

const levels = [
  "Novice Explorer",
  "Curious Seeker",
  "Problem Pioneer",
  "Knowledge Scout",
  "Solution Architect",
  "Master Analyst",
  "Innovation Leader",
  "Wisdom Sage",
  "Knowledge Vanguard",
  "Academic Titan",
];

const genderArray1 = [
  { label: "Male", value: "1" },
  { label: "Female", value: "2" },
  { label: "Other", value: "3" },
];



const relations = [
  { label: "Father", value: "father" },
  { label: "Mother", value: "mother" },
  { label: "Guardian", value: "guardian" },
  { label: "Brother", value: "brother" },
  { label: "Sister", value: "sister" },
  { label: "Uncle", value: "uncle" },
  { label: "Aunt", value: "aunt" },
  { label: "Grandfather", value: "grandfather" },
  { label: "Grandmother", value: "grandmother" },
  { label: "Other", value: "other" },
];

const compCategory = [
  { label: "Junior", value: "JUNIOR" },
  { label: "Sub-Junior", value: "SUB-JUNIOR" },
  { label: "Senior", value: "SENIOR" },
];

const compSubject = [
  { label: "Drawing", value: "Drawing" },
  { label: "Quiz", value: "Quiz" },
  { label: "Creative Thinking", value: "Creative Thinking" },
];

const jobFunctions = [
  "Application Development",
  "Product Development",
  "Human Resources in IT",
  "Software Testing",
  "Network Administration",
  "Database Administration",
  "Cybersecurity",
  "Cloud Computing",
  "Data Analysis",
  "Data Science",
  "DevOps Engineering",
  "System Engineering",
  "Technical Support",
  "IT Project Management",
  "Business Intelligence",
  "Technical Writing",
  "UI/UX Design",
  "Software Architecture",
  "IT Consulting",
  "Infrastructure Management",
  "Network Security",
  "Mobile App Development",
  "Web Development",
  "ERP Implementation",
  "Software Maintenance",
  "AI & Machine Learning",
  "Blockchain Development",
  "Quality Assurance (QA)",
  "Systems Analysis",
  "Firmware Development",
  "Security Operations Center (SOC) Analyst",
  "Technical Sales",
  "IT Audit and Compliance",
  "Software Configuration Management",
  "Big Data Engineering",
  "Network Engineering",
  "Systems Integration",
  "Virtualization Engineering",
  "Technical Training & Development",
  "SaaS Operations",
  "CRM Development & Support",
  "Hardware Engineering",
  "Technical Account Management",
  "Data Warehouse Development",
  "Geographic Information Systems (GIS)",
  "IT Procurement & Vendor Management",
  "Technical Program Management",
  "Cloud Security",
  "Ethical Hacking/Penetration Testing",
  "Technical Recruiter",
  "Data Engineer",
  "Solutions Architect",
  "Security Analyst",
  "Automation Engineer",
  "Release Management",
  "IT Asset Management",
  "Disaster Recovery Planning",
  "Mainframe Operations",
  "Embedded Systems Development",
  "Network Design",
  "Compliance & Risk Management",
  "Technical Customer Support",
  "Technical Operations",
  "Software Licensing Management",
  "Data Governance",
  "Telecommunications Engineering",
  "Penetration Tester",
  "IT Strategy & Planning",
  "Software Development Lifecycle (SDLC) Management",
  "Performance Testing",
  "Technical Account Executive",
  "Cloud Infrastructure Engineer",
  "Data Privacy Officer",
  "Technical Business Analyst",
  "Software Deployment Engineer",
  "Middleware Support",
  "Technical Vendor Support",
  "IT Policy Development",
  "E-commerce Platform Development",
  "Augmented Reality (AR) & Virtual Reality (VR) Development",
  "User Support Specialist",
  "Computer Forensics",
  "Network Operations Center (NOC) Technician",
  "System Administrator",
  "Technical Solutions Engineer",
  "IoT (Internet of Things) Development",
  "Technical Product Manager",
  "Remote Infrastructure Support",
  "Software Localization & Internationalization",
  "SaaS Product Owner",
  "Technology Evangelist",
  "Software Licensing and Compliance",
  "Technical Data Analyst",
  "Cloud Migration Specialist",
  "Open Source Software Development",
  "Mobile Device Management (MDM)",
  "Technical Incident Response",
  "Augmented Reality (AR) Developer",
  "Technical Vendor Negotiator",
  "IT Service Management (ITSM) Specialist",
  "Software Packaging and Deployment",
  "Network Operations Engineer",
  "Data Center Operations",
  "Technical Account Manager",
  "Virtual Desktop Infrastructure (VDI) Specialist",
  "Augmented Reality Developer",
  "Software Development Manager",
  "IT Infrastructure Auditor",
  "Technical Sales Engineer",
  "Application Support Analyst",
  "Cloud Solutions Architect",
  "Network Operations Center (NOC) Manager",
  "Data Integration Specialist",
  "Automation Tester",
  "Data Visualization Specialist",
  "Technical Content Developer",
  "Security Software Developer",
  "Digital Transformation Consultant",
  "Cybersecurity Analyst",
  "Incident Response Coordinator",
  "Technical System Analyst",
  "Customer Success Manager (IT)",
  "Application Support Engineer",
  "Network Security Engineer",
  "Cloud Operations Engineer",
  "Data Quality Analyst",
  "Software Performance Tester",
  "Security Compliance Officer",
  "IoT Security Specialist",
  "Information Security Manager",
  "Data Governance Lead",
  "Technical Data Scientist",
  "Cloud Infrastructure Administrator",
  "Virtualization Support Engineer",
  "Cloud Cost Optimization Analyst",
  "Technical Account Director",
  "Network Risk Analyst",
  "Software Release Coordinator",
  "IT Service Desk Technician",
  "Systems Programmer",
  "Technical Solutions Consultant",
  "Data Migration Specialist",
  "Remote Support Technician",
  "Application Security Engineer",
  "Network Infrastructure Engineer",
  "Software Configuration Analyst",
  "Data Center Network Engineer",
  "Security Operations Analyst",
  "Software Quality Engineer",
  "Digital Forensics Analyst",
  "Systems Capacity Planner",
  "EDI (Electronic Data Interchange) Specialist",
  "Network Protocol Engineer",
  "Cloud Security Architect",
  "Technical Program Coordinator",
  "Software Product Owner",
  "IT Vendor Relationship Manager",
  "Network Troubleshooting Specialist",
  "Cloud Native Engineer",
  "Data Privacy Analyst",
  "Technical Documentation Specialist",
  "Software Licensing Analyst",
  "Hardware Support Technician",
  "Network Performance Engineer",
  "Cloud Backup & Recovery Specialist",
  "Data Analytics Engineer",
  "Application Performance Engineer",
  "Virtualization Infrastructure Engineer",
  "Technical Solutions Architect",
  "Network Compliance Analyst",
  "Quantum Computing Researcher",
  "Hardware Design Engineer",
  "Embedded Software Engineer",
  "Software Implementation Specialist",
  "IT Asset Disposition Specialist",
  "Data Pipeline Developer",
  "Technical Content Strategist",
  "Cloud Network Engineer",
  "Software Release Manager",
  "Security Incident Analyst",
  "Data Center Technician",
  "Technical Support Engineer",
  "Software Localization Engineer",
  "Network Security Auditor",
  "Cloud Operations Manager",
  "Systems Integration Engineer",
  "Penetration Testing Consultant",
  "IT Governance Specialist",
  "Software Development Coordinator",
  "Data Operations Manager",
  "Technical Customer Success Specialist",
  "Cloud Compliance Analyst",
  "Application Lifecycle Manager",
  "Network Automation Engineer",
  "IT Infrastructure Project Coordinator",
  "Data Security Analyst",
  "Cloud Adoption Strategist",
  "Software Development Lead",
  "Network Design Engineer",
  "Technical Solutions Sales Specialist",
  "Data Platform Engineer",
  "Software Deployment Specialist",
  "Cloud Data Engineer",
  "Technical Compliance Auditor",
  "Cybersecurity Governance Lead",
  "Software Test Automation Engineer",
  "Data Modeling Specialist",
  "IT Process Improvement Specialist",
  "Cloud Platform Engineer",
  "Application Performance Monitoring Engineer",
  "Network Operations Officer",
  "Technical Customer Engagement Manager",
  "Data Platform Architect",
  "Security Incident Response Lead",
  "Cloud Infrastructure Support Technician",
  "Software Quality Assurance Lead",
  "Network Security Manager",
  "Digital Workplace Specialist",
  "Data Privacy Engineer",
  "Cloud Migration Engineer",
  "Application Security Architect",
  "Technical Sales Support Specialist",
  "Data Storage Engineer",
  "Network Security Consultant",
  "Cloud Platform Support Engineer",
  "Software Configuration Manager",
  "Technical Training Specialist",
  "Data Engineering Lead",
  "Network Operations Supervisor",
  "IoT Solution Architect",
  "Cloud Security Engineer",
  "Application Monitoring Engineer",
  "Data Orchestration Engineer",
  "VPN & Remote Access Engineer",
  "Software Development Operations (DevOps) Lead",
  "Cloud Security Operations Center (SOC) Analyst",
  "Technical Product Owner",
  "Data Infrastructure Engineer",
  "Network Automation Developer",
  "Security Compliance Auditor",
  "Cloud Cost Management Analyst",
  "Systems Test Engineer",
  "Application Infrastructure Engineer",
  "Data Security Officer",
  "Network Capacity Planner",
  "Cloud Data Platform Developer",
  "Technical Support Manager",
  "Data Quality Engineer",
  "Network Forensics Specialist",
  "Cloud Security Policy Analyst",
  "Application Performance Tester",
  "IT Compliance Auditor",
  "Software Development Coach",
  "Network Protocol Analyst",
  "Cloud Infrastructure Security Engineer",
  "Data Governance Analyst",
  "Technical Customer Experience Designer",
  "Network Optimization Engineer",
  "Cloud Operations Analyst",
  "Application Security Tester",
  "Data Migration Engineer",
  "Network Security Engineer Lead",
  "Cloud Automation Engineer",
  "Software Deployment Manager",
  "Security Vulnerability Analyst",
  "Data Privacy Compliance Officer",
  "Network Monitoring Specialist",
  "Cloud Network Security Engineer",
  "Software Reliability Engineer",
  "DevSecOps Engineer",
  "Application Development Lead",
  "Data Warehouse Architect",
  "Network Security Operations Analyst",
  "Cloud Infrastructure Engineer II",
  "IT Service Delivery Manager",
  "Data Center Operations Manager",
  "Technical Product Evangelist",
  "Cloud Systems Engineer",
  "Application Optimization Engineer",
  "Network Security Compliance Analyst",
  "Data Analytics Manager",
  "Cloud Data Security Specialist",
  "Software Engineering Manager",
  "Software Engineering",
  "Technical Solutions Engineer II",
  "Data Integration Engineer",
  "Network Security Operations Lead",
  "Cloud Infrastructure Consultant",
  "Application Platform Engineer",
  "Data Privacy & Security Analyst",
  "Network Automation Architect",
  "Cloud Infrastructure Project Manager",
  "Software Release Engineer",
  "Security Architecture Engineer",
  "Data Engineering Manager",
  "Network Optimization Specialist",
  "Cloud Security Operations Specialist",
  "Application Security Lead",
  "Data Science Lead",
  "Network Engineering Manager",
  "Cloud Infrastructure Operations Lead",
  "Software Development Operations (DevOps) Engineer",
  "Data Platform Support Engineer",
  "Network Operations Technician",
  "Cloud Security Analyst",
  "Application Support Lead",
  "Data Governance Lead",
  "Network Security Threat Analyst",
  "Cloud Infrastructure Deployment Engineer",
  "Software Quality Assurance Tester",
  "Security Incident Handler",
  "Data Privacy & Compliance Engineer",
  "Network Troubleshooting Engineer",
  "Cloud Network Architect",
  "Application DevOps Engineer",
  "Data Management Specialist",
  "Internship",
  'IoT (Internet of Things) Development',
  'IoT Solution Architect',
   'MLOps Engineer'
];

const pricingPlans = [
  {
    title: "Free",
    description: "Get started with basic access to job posting or applying.",
    features: [
      { label: "1 Job Post / Month", highlight: true }, 
      { label: "2 Mock Interview / Month", highlight: true }, 
      { label: "Basic JD & Question Generator", highlight: true },
      { label: "Limited Analytics Access", highlight: false },
      { label: "No Voice Interview Access", highlight: false },
    ],
    prices: {
      "1month": 0,
      "3month": 0,
      "6month": 0,
      lifetime: 0,
    },
  },
  {
    title: "Starter",
    description:
      "Ideal for startups or individuals hiring or preparing for interviews.",
    features: [
      { label: "5 Job Posts / Month", highlight: true },
      { label: "5 Mock Interviews / Month", highlight: true },
      { label: "AI JD & Question Generator", highlight: true },
      { label: "Basic Analytics", highlight: true },
      { label: "Email Support", highlight: true },
    ],
    prices: {
      "1month": 499,
      "3month": 1299,
      "6month": 2299,
      lifetime: 3999,
    },
  },
  {
    title: "Growth",
    description:
      "For teams growing fast, hiring at scale or job seekers upskilling.",
    features: [
      { label: "20 Job Posts / Month", highlight: true },
      { label: "10 Mock Interviews / Month", highlight: true },
      { label: "Advanced Analytics & Scoring", highlight: true },
      { label: "5 Video Interviews / Month", highlight: true },
      { label: "Priority Email Support", highlight: true },
    ],
    prices: {
      "1month": 1499,
      "3month": 3999, // ~11% off
      "6month": 7299, // ~18% off
      lifetime: 10999, // ~39% off
    },
  },
  // {
  //   title: "Enterprise",
  //   price: 0,
  //   originalPrice: 0,
  //   period: "month",
  //   description: "Custom plan for high-volume hiring or career partners.",
  //   features: [
  //     { label: "Unlimited Job Posts & Interviews", highlight: true },
  //     { label: "Full Access to Analytics", highlight: true },
  //     { label: "Dedicated Account Manager", highlight: true },
  //     { label: "Team Member Access", highlight: true },
  //   ],
  //   zIndex: 3,
  // },
];

const experienceLevels = ["Fresher", "Junior", "Mid-Level", "Lead", "Director"];


  const evaluationCategories = [
    "Technical Competence",
    "Cognitive Ability",
    "Communication & Collaboration",
    "Leadership & Initiative",
    "Cultural Fit & Integrity",
  ];
export {
  addressType,
  amounts,
  appointmentTypes,
  BrandsList,
  buttons,
  buttons1,
  buttons2,
  buttons3,
  cameraType,
  cancellationReasons,
  categories,
  categoryArray,
  compCategory,
  compSubject,
  contactConnectType,
  contactStatusType,
  countryList,
  courseCategory,
  courseRatings,
  courses,
  criticalityArray,
  currencies,
  DEcategories,
  dietitianSpecialties,
  difficultyLevel,
  doctorSpecialities,
  durationPeriodArray, evaluationCategories, experienceLevels, experienceRequired,
  familyRelationships,
  filmingOptions,
  foodType,
  fuels,
  genderArray, genderArray1, healthEntityType, jobFunctions,
  jobMode, jobShift, jobType,
  jobTypeArray,
  labTestData,
  languages,
  levels,
  microphoneType,
  noOfQos,
  nurseSpecialties,
  operatingSystem,
  orderFilter, payroll, permitType,
  pharmacistSpecialtyData,
  platformFee, pricingPlans, priorityArray,
  productDisplayType,
  puc,
  purposeofUse,
  QnsFilterBy,
  QnsSortBy,
  QnsTypeSortBy,
  relations,
  returnReason,
  roles,
  shippingFee,
  skillLevels,
  societyRole,
  stateArray,
  storeType,
  strokes,
  subCategoryArray,
  time,
  units,
  userDeleteType,
  userSecurityType,
  userTypeArray,
  vehicleBodies,
  vehicleCategories,
  vehicleOptions,
  vehicleType,
  weekDays,
  workTypeArray
};

